/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerEnv` (hash: 37b88b7c42ec43a49aaf67bdfe948e48)
interface __BaseEnv_WorkerEnv {
	ORIGIN_URL: "https://functions.yandexcloud.net/d4e3h1o2eoa1vp5g7ec5";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ORIGIN_URL">> {}
}
